### ISSUE TITLE
Convert to a "Halite style" cookbook.

### ISSUE THREAD

**Issue by johnbellone** [sethvargo/chef-sugar#105]
@coderanger has recently pushed out the [poise-service library cookbook](https://github.com/poise/poise-service) which is a [Halite style cookbook](https://coderanger.net/state-of-the-onion-may-26/). I wanted to reach out to you first to figure out if you'd accept a patch to do so with the Chef Sugar cookbook instead of maintaining an internal fork of the cookbook.

My main motivation here is we would no longer need to distribute Chef Sugar as a gem. This proves problematic for those of us that are in an enterprise setting. Even though cookbook updates can happen out of band we're still using the `chef_gem` LWRP to include it.

My proposed changes are quite straightforward and simple:
1. Add the [Halite extension to Berksfile](https://github.com/poise/poise/blob/master/Berksfile#L20-L22).
2. Modify the default recipe to simply `require 'chef/sugar'`.
3. Modify the Gem specification to add [Halite as a dependency](https://github.com/poise/poise/blob/master/poise.gemspec#L36)

You can see examples:
- [Poise cookbook](https://github.com/poise/poise)
- [Poise Service cookbook](https://github.com/poise/poise-service)

**Comment by sethvargo** [comment]
Hi @johnbellone 

Until Halite gets more traction and adoption in the Chef community, I will not be merging support for it. Chef sugar is dep-minimal and I prefer to keep it that way. Sorry! :smile:
