### ISSUE TITLE
Undefined node attribute or method `deep_fetch' on `node'

### ISSUE THREAD

**Issue by jakshi** [sethvargo/chef-sugar#107]
I tried to use this cookbook deep_fetch method and it fails with:

```
Undefined node attribute or method `deep_fetch' on `node'
```

I added 
```
depends 'chef-sugar'
```
to Berksfile and 
```
include_recipe 'chef-sugar::default'
```
to our base role cookbook.

I'm not sure is it a bug or expected behavior, may be I missed some configuration steps?

I use debian and chef-client 12.0.3.

I would be grateful for any clues.

**Comment by sethvargo** [comment]
Can you share your recipe? You probably have the catch-22 where you need to have chef-sugar installed first.

**Comment by jakshi** [comment]
Hello Seth,

It's company internal recipes, so I probably a bad idea to share all the code. 

Parts of recipes that are related to chef-sugar looks like:

binary_role_common cookbook (it's in every host run_list):

recipe/default.rb
```
include_recipe 'chef-sugar::default'
...
include_recipe 'binary_wrapper_postfix'
...
```

metadata.rb

```
name 'binary_role_common'
...
depends 'chef-sugar'
```

binary_wrapper_postfix cookbook

attributes/default.rb

```
if node.deep_fetch('cloud','provider') && node['cloud']['provider'] == 'gce'
  default['postfix']['main']['relayhost'] = '[smtp.mandrillapp.com]:2525'
...
else
  default['postfix']['main']['relayhost'] = '[smtp.mandrillapp.com]'
...
end
```

**Comment by sethvargo** [comment]
Yea, that's what I thought. You can't use it in attributes because attributes are loaded before recipes. You need to bootstrap your node with chef-sugar pre-installed into Chef if you want to use Chef Sugar in an attributes file.

**Comment by jakshi** [comment]
Thank you for the answer.
I wonder - are there a way to load it before attributes.

There are definitely a cases (like this one, or when you want to update chef-client with chef-client or whatever) when you would like to run chef-client to run twice with different set of cookbooks.

**Comment by sethvargo** [comment]
@jakshi nope. It's just not possible. You need to use a custom bootstrap script to install chef-sugar as part of the chef installation if you want that. Sorry. Attributes are loaded before recipes, so there's just no way.
