### ISSUE TITLE
chef-sugar with chefdk

### ISSUE THREAD

**Issue by pantocrator27** [sethvargo/chef-sugar#109]
Hello.  Admittedly I am new to the Ruby and Chef eco-system so this is probably something I am doing.  I am using Ruby that comes with ChefDK.  I have imported chef-ruby into my cookbook via including it in metadata.rb.  Also I executed chef exec gem install chef-sugar.  However when I am testing my cookbook i am getting an error that it could not "require chef/sugar".

Any assistance would be greatly appreciated!

**Comment by sethvargo** [comment]
Hi @pantocrator27 

Can you please share your cookbook and the complete error output? How are you using Chef Sugar?

**Comment by pantocrator27** [comment]
Here is my repo: https://github.com/pantocrator27/cookbook-nginx-repo
Here is the error: http://pastebin.com/5J3ud6ws

As I mentioned, I am using the ChefDK and running the command "chef shell-init bash" to include ChefDK in my environment.  

RIght now, I am merely trying to "include_recipe 'chef-sugar::default' in my default recipe.  I have included chef-sugar in my metadata.rb file and this is being picked up by my Berksfile.  

Thanks @sethvargo!

**Comment by sethvargo** [comment]
Hi @pantocrator27 

What version of Chef are you using? @lamont-granquist if you use `compile_time true`, does that automatically require the library and add it to the loadpath?

**Comment by pantocrator27** [comment]
When I run chef-v, I get the following output:

Chef Development Kit version: 0.6.2
chef-client version: 12.3.0
berks version: 3.2.4
kitchen version: 1.4.0

**Comment by lamont-granquist** [comment]
it doesn't require it or add it to the load path.  it does a clear_paths (IIRC) to nuke the in-memory cache so that a later require can pick it up.

**Comment by lamont-granquist** [comment]
i don't see any error with the code and can't determine what the problem is from the pasebin output.

about all i can think of is that its somehow being run in a bundle and chef-sugar isn't in the bundle, but there's no Gemfile in the repo.

**Comment by pantocrator27** [comment]
using rake that comes bundled with ChefDK, I am running "rake unit" if that helps ...

**Comment by pantocrator27** [comment]
I tried adding the Gemfile prior to running rake unit again and it still gives the same error

**Comment by pantocrator27** [comment]
Hey @sethvargo @lamont-granquist 

I think I resolved my issue ... running chef shell-init bash set and my GEM_HOME and GEM_PATH to the root user's home directory.  Once I changed this, I was good to go.

Thank you ever so much for your time and assistance!
