### ISSUE TITLE
chef-sugar fails to upload

### ISSUE THREAD

**Issue by vinyar** [sethvargo/chef-sugar#120]
Ahoy, I seem to be hitting an odd error. Info and repo below

TLDR:
Chef sugar can not be uploaded after being downloaded.

Details:
The upload issue is observed on Ubuntu 12.x under the following conditions:
`knife cookbook upload` with chef client 11.6.x
`knife cookbook upload` with chef client 11.18.x
`knife cookbook upload` with chefdk 0.7.0
`knife backup restore`
chef-server 12.2 migration 

Workarounds:
manually set the cookbook version to explicit string.

repro:
```
my@sandwitch ~/temp/cookbooks2 $ git clone git@github.com:sethvargo/chef-sugar.git
Cloning into 'chef-sugar'...
remote: Counting objects: 1449, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 1449 (delta 0), reused 0 (delta 0), pack-reused 1444
Receiving objects: 100% (1449/1449), 398.72 KiB | 0 bytes/s, done.
Resolving deltas: 100% (719/719), done.
Checking connectivity... done.
my@sandwitch ~/temp/cookbooks2 $ cd ..
my@sandwitch ~/temp $ knife cookbook upload chef-sugar -c ~/.chef/knife.rb -o ./cookbooks2
Uploading chef-sugar     [3.1.1]
Uploaded 1 cookbook.
```
```
my@sandwitch ~/temp $ mkdir cookbooks3
my@sandwitch ~/temp $ knife cookbook download chef-sugar -c ~/.chef/knife.rb -d ./cookbooks3
Downloading chef-sugar cookbook version 3.1.1
Downloading resources
Downloading providers
Downloading recipes
Downloading definitions
Downloading libraries
Downloading attributes
Downloading files
Downloading templates
Downloading root_files
Cookbook downloaded to ./cookbooks3/chef-sugar-3.1.1
my@sandwitch ~/temp $ knife cookbook upload chef-sugar -c ~/.chef/knife.rb -o ./cookbooks3
ERROR: LoadError: cannot load such file -- /..../temp/cookbooks3/chef-sugar-3.1.1/lib/chef/sugar/version
my@sandwitch ~/temp $
````

**Comment by rmoriz** [comment]
Probably caused by using Ruby code to load the version constant:
https://github.com/sethvargo/chef-sugar/blob/master/metadata.rb#L17-L18

**Comment by vinyar** [comment]
@rmoriz 2.3.2 works fine. Anything newer fails with error above.
I had a PR but I am not 100% it's the best fix. Hacked it up as a work around: https://github.com/sethvargo/chef-sugar/pull/118
