### ISSUE TITLE
Cannot upload cookbook to local supermarket.

### ISSUE THREAD

**Issue by yurylevin** [sethvargo/chef-sugar#131]
Hi,

I'm trying to upload cookbook https://github.com/sethvargo/chef-sugar/ to local supermarket and it fails because of format of version metadata.rb. It's version Chef::Sugar::VERSION while number is expected. Do you know how to upload such cookbooks?

Thanks,
Yury.

**Comment by sethvargo** [comment]
Yes, do not use `knife cookbook upload` because it uploads uncompiled metadata which is both insecure and not guaranteed to be portable. Use a tool like Stove or compile the metadata.json yourself before uploading.
