### ISSUE TITLE
HEADSUP: docker? sugar being added directly to chef-core

### ISSUE THREAD

**Issue by lamont-granquist** [sethvargo/chef-sugar#134]
chef/chef#4979 adds docker? sugar directly in chef-core.  should probably look that over and figure out if we need to change that code and/or do some handshaking around one or the other version winning.

i'm actually kind of okay with chef-sugar monkeypatching over the top of it, then people can include chef-sugar and get improvements that back-port to old chef-client versions...

could use your eyeballs on it thought @sethvargo.

if you're cool with it, just close this issue.

**Comment by sethvargo** [comment]
The method airty is the same, so it shouldn't be a problem. Maybe push an addition to that comment that, if a user includes Chef Sugar, sugar will overwrite that method?
