### ISSUE TITLE
IP support for bare metal?

### ISSUE THREAD

**Issue by jwmarshall** [sethvargo/chef-sugar#135]
Right now the `best_ip_for` method really only supports cloud deployments. Is there any hope for support for bare metal deployments where machines have multiple interfaces (e.g. public/private LAN)? Right now I'm using my own custom method that also requires a node attribute identifying the private interface.

**Comment by sethvargo** [comment]
Hi there,

I would gladly accept a pull request for this functionality.

**Comment by jwmarshall** [comment]
What's the best way to test changes to the chef-sugar gem using my clone of this cookbook? I've made some changes and linked local cookbook via Berkshelf but the resulting `chef-sugar` gem that the default  recipe installs obviously doesn't have my changes.

**Comment by jwmarshall** [comment]
My (untested) modification is here: https://github.com/jwmarshall/chef-sugar/blob/feature/baremetal_ip/lib/chef/sugar/ip.rb

**Comment by jwmarshall** [comment]
As a hack I'm just replacing `ip.rb` inside the chef_gem on my test kitchen machine for now.
