### ISSUE TITLE
incompatible with policy files 

### ISSUE THREAD

**Issue by lmunro** [sethvargo/chef-sugar#137]
When converging with policyfiles, the following error is generated:

>  STDERR: ERROR:  Could not find a valid gem 'chef-sugar' (= 66917636236862495.4313951758292554.152016834041753) in any repository
>          ERROR:  Possible alternatives: chef-sugar
>          ---- End output of /opt/chef/embedded/bin/gem install chef-sugar -q --no-rdoc --no-ri -v "66917636236862495.4313951758292554.152016834041753" ----
>          Ran /opt/chef/embedded/bin/gem install chef-sugar -q --no-rdoc --no-ri -v "66917636236862495.4313951758292554.152016834041753" returned 2

This is due to the cookbook version format from [https://github.com/sethvargo/chef-sugar/blob/master/recipes/default.rb#L20](url) returning the policyfile cookbook version format instead of the metadata version.

Perhaps we should be able to override this by passing through an attribute and setting the default value of the attribute to 
 `run_context.cookbook_collection[cookbook_name].metadata.version` ?

**Comment by johnbellone** [comment]
We use this perfectly fine with policyfiles, what does your Policyfile.rb look like?

**Comment by tas50** [comment]
There's nothing in this cookbook that should prevent it working with policy files. Closing out due to lack of response.
