### ISSUE TITLE
[feature] kernel release checks

### ISSUE THREAD

**Issue by AVVS** [sethvargo/chef-sugar#141]
Currently what I have to do is somewhat along these lines:

``` rb
KernelRelease = node[:kernel][:release].split('-')[0]
if constraint('>= 4.0.0').satisfied_by?(KernelRelease) then
  ...
end
```

Would be nice to have smth like this: `kernel?('>= 4.0.0')`

**Comment by sethvargo** [comment]
Hi @AVVS 

We'd accept a PR for this, but I don't think it's something we'll implement on our own. Thanks! 😄
