### ISSUE TITLE
(Question) require chef-sugar in custom resource

### ISSUE THREAD

**Issue by jharshman** [sethvargo/chef-sugar#144]
I am running into an issue utilizing chef-sugar in my custom resource.

``` ruby
include Chef::Sugar::Init

is_systemd = '.service' unless Chef::Sugar::Init.upstart?(Chef::Node)
init_root = '/etc/systemd/system' unless Chef::Sugar::Init.upstart?(Chef::Node)
```

```
       NameError
       ---------
       uninitialized constant Chef::Sugar
```

Fails on the include.  I noticed that there was a similar problem https://github.com/sethvargo/chef-sugar/issues/73 that was resolved by `require 'chef/sugar`.  Unfortunately this doesn't appear to solve my problem as I get a LoadError.

If you could point me in the right direction on this, that would be greatly appreciated. 

Thanks!

**Comment by tas50** [comment]
Make sure to do the require within the action class if you're using it in the actions

action_class do
  require 'chef/sugar'
end
