### ISSUE TITLE
method access to node attributes (node.foo.bar) is deprecated and will be removed in Chef 13

### ISSUE THREAD

**Issue by johntdyer** [sethvargo/chef-sugar#146]
I am getting the following deprecation warnings when using chef-sugar 

```shell
  "method access to node attributes (node.foo.bar) is deprecated and will be removed in Chef 13, please use bracket syntax (node["foo"]["bar"]) at 1 location:
    - /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-sugar-3.4.0/lib/chef/sugar/node.rb:162:in `method_missing'
```

**Comment by drenalin23** [comment]
In case some expanded context helps, here is what I see.

```
Please see https://docs.chef.io/deprecations_attributes.html for further details and information on how to correct this problem. at /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44/lib/chef/event_dispatch/dispatcher.rb:43:in `call'
.[2017-02-02T16:11:53-08:00] WARN: method access to node attributes (node.foo.bar) is deprecated and will be removed in Chef 13, please use bracket syntax (node["foo"]["bar"]) (CHEF-4)/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-sugar-3.4.0/lib/chef/sugar/node.rb:162:in `method_missing'.
```

**Comment by kriszentner** [comment]
I tested Chef Sugar 3.6.0 on Chef Client 13.6.4. In spite of there being deprecation warnings in Chef 12.20.3, I didn't see the same warnings in the Chef 13 client, so this could be a bug in the way that Chef12 is detecting the error. I'd recommend testing with the Chef 13 client and seeing if this is still an issue. I believe this may be a false positive.

**Comment by tas50** [comment]
This is a false alarm in the Chef 12 deprecation warning since chef-sugar is monkey patching itself into the chef code. This code will continue to work as expected in Chef 13
