### ISSUE TITLE
vagrant? does not return correct value when cookbook vagrant is being used

### ISSUE THREAD

**Issue by mwolny** [sethvargo/chef-sugar#150]
**BACKGROUND**
Method `vagrant?` returns `true` when cookbook vagrant is being used because `vagrant_key?` returns `true`. Cookbook `vagrant` creates `node['vagrant']`. Since `vagrant_key?` exists because of legacy reasons, maybe it's time to remove this code? WDYT?

**Comment by sethvargo** [comment]
I think it works in 99.99% of use cases, which is what most people want. I would argue this is a bug in the Vagrant cookbook tbh.
