### ISSUE TITLE
virtual? checks that a virtualization install exists, but not if we're host or guest

### ISSUE THREAD

**Issue by sgtcoolguy** [sethvargo/chef-sugar#151]
I incorrectly assumed virtual? only returned true if we're running from inside a virtualization method as a guest, but it does not consult the "role" value to determine if we're "host" or "guest".

This may be intentional, but it was certainly confusing/surprising at first. Perhaps additional methods to expose if we're the virtual host or guest?

(See https://github.com/chef/ohai/blob/master/lib/ohai/plugins/linux/virtualization.rb)

**Comment by sethvargo** [comment]
This is working as intended, but you're right that additional information would be helpful. Please feel free to submit a PR to add differentiation between host and guest 😄
