### ISSUE TITLE
Deprecation error with syntax blocker for Chef13

### ISSUE THREAD

**Issue by seankaufman** [sethvargo/chef-sugar#155]
Bumping: https://github.com/sethvargo/chef-sugar/issues/146

Deprecation errors still present and will break cookbook in Chef13.

```
         method access to node attributes (node.foo.bar) is deprecated and will be removed in Chef 13, please use bracket syntax (node["foo"]["bar"]) at 1 location:
           - /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-sugar-3.5.0/lib/chef/sugar/node.rb:162:in `method_missing'
          See https://docs.chef.io/deprecations_attributes.html for further details.
```

**Comment by jshrack-ssi** [comment]
This is definitely an issue. Any chance it will be fixed soon?

**Comment by tas50** [comment]
This is a false alarm in the Chef 12 deprecation warning since chef-sugar is monkey patching itself into the chef code. This code will continue to work as expected in Chef 13
