### ISSUE TITLE
No chef-sugar 3.6.0 gem in rubygems.org

### ISSUE THREAD

**Issue by angelosanramon** [sethvargo/chef-sugar#159]
Just pulled the 3.6.0 release. Now getting the following error:

       Recipe: chef-sugar::default
         * chef_gem[chef-sugar] action install[2017-10-26T14:13:40-07:00] WARN: failed to find gem chef-sugar (= 3.6.0) from [https://www.rubygems.org]

           ================================================================================
           Error executing action `install` on resource 'chef_gem[chef-sugar]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '2'
           ---- Begin output of /opt/chef/embedded/bin/gem install chef-sugar -q --no-rdoc --no-ri -v "3.6.0" --source=https://www.rubygems.org ----
           STDOUT:
           STDERR: ERROR:  Could not find a valid gem 'chef-sugar' (= 3.6.0) in any repository
           ERROR:  Possible alternatives: chef-sugar
           ---- End output of /opt/chef/embedded/bin/gem install chef-sugar -q --no-rdoc --no-ri -v "3.6.0" --source=https://www.rubygems.org ----
           Ran /opt/chef/embedded/bin/gem install chef-sugar -q --no-rdoc --no-ri -v "3.6.0" --source=https://www.rubygems.org returned 2

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/chef-sugar/recipes/default.rb:23:in `from_file'
           /tmp/kitchen/cache/cookbooks/firewall/recipes/default.rb:20:in `from_file'
           /tmp/kitchen/cache/cookbooks/zis-baseconfig/recipes/firewall.rb:1:in `from_file'
           /tmp/kitchen/cache/cookbooks/zis-baseconfig/recipes/default.rb:16:in `from_file'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/chef-sugar/recipes/default.rb

            23:   chef_gem 'chef-sugar' do
            24:     version gem_version
            25:     compile_time true
            26:   end
            27: else

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/chef-sugar/recipes/default.rb:23:in `from_file'

           chef_gem("chef-sugar") do
             package_name "chef-sugar"
             action [:install]
             default_guard_interpreter :default
             declared_type :chef_gem
             cookbook_name "chef-sugar"
             recipe_name "default"
             version "3.6.0"
             compile_time true
           end

           System Info:
           ------------
           chef_version=13.5.3
           platform=centos
           platform_version=7.4.1708
           ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
           program_name=chef-client worker: ppid=29554;start=14:13:37;
           executable=/opt/chef/bin/chef-client

**Comment by tas50** [comment]
The gem has been pushed to rubygems now
