### ISSUE TITLE
Cannot load such file chef/sugar

### ISSUE THREAD

**Issue by Nokel81** [sethvargo/chef-sugar#162]
A cookbook stopped working today after pulling the latest version of this cookbook with the following error:

```
  
=========================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/chef-sugar/libraries/chef-sugar.rb
       =========================================================================

       LoadError
       ---------
       cannot load such file -- chef/sugar

       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/chef-sugar/libraries/chef-sugar.rb:1:in `<top (required)>'

       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/chef-sugar/libraries/chef-sugar.rb:

         1>> require "chef/sugar"
         2:
```

This happens right after the compiling cookbooks step

**Comment by tas50** [comment]
@Nokel81 What version of chef-client are you running?

**Comment by Nokel81** [comment]
chef-client version: 13.6.4

**Comment by Nokel81** [comment]
Reverting to chef-sugar 3.6.0 no longer throws this error

**Comment by ross-bragg** [comment]
I get this error as well on Chef 12.4.1.

**Comment by tas50** [comment]
I'm looking into the Chef 13 failures, but Chef 12.4 is definitely not supported at this point. That came out back in Sept 2015 and lots of new functionality has shipped since then. Also 12.X goes EOL in April.

**Comment by tas50** [comment]
@Nokel81 Is it possible to see the complete cookbook where this code is being used? I just created a test cookbook and I wasn't able to repro this issue with 4.0

**Comment by Nokel81** [comment]
I don't think that that is required since though I have chef-client version 13.X on my personal machine the provisioner is using chef-client version 12.X so I believe that that is the problem. And until some other cookbooks upgrade we maybe stuck.

**Comment by ndobson** [comment]
I've also started seeing this error as well with my chefspec tests, had to add chef-sugar to my Gemfile. Didn't get it with 3.6.0

**Comment by rmoriz** [comment]
try to install the `chef-sugar` gem, either via Gemfile in your cookbook or in your chefdk environment(`chef gem install chef-sugar`).

**Comment by sethvargo** [comment]
Closing since Chef 12 is officially EOL now 😄

**Comment by matkam** [comment]
Seeing the same issue on the latest Chef, version 14.4.56. I tried installing both chef-sugar 4.1.0 and 3.6.0 using `chef gem install chef-sugar -v 3.6.0` after `chef gem uninstall chef-sugar`.

```
Installing Cookbook Gems:
Compiling Cookbooks...

================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/chef-sugar/libraries/chef-sugar.rb
================================================================================

LoadError
---------
cannot load such file -- chef/sugar

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/chef-sugar/libraries/chef-sugar.rb:1:in `<top (required)>'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/chef-sugar/libraries/chef-sugar.rb:

  1>> require "chef/sugar"
  2:  

System Info:
------------
chef_version=14.4.56
platform=ubuntu
platform_version=14.04
ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
program_name=/usr/bin/chef-client
executable=/opt/chef/bin/chef-client
```

**Comment by matkam** [comment]
Never mind. I think it was a problem with a bad upgrade from chef 12 to 14. I uninstalled Chef, manually removed the `/opt/chef` directory, then reinstalled Chef 14. All good now.
