### ISSUE TITLE
Ruby version installation and Chef dependency problem

### ISSUE THREAD

**Issue by rmldsky** [sethvargo/chef-sugar#163]
`chef-sugar` depends on Ruby 2.2.2+:
```
Gem::InstallError: chef-sugar requires Ruby version >= 2.2.2.
```
In `metadata.rb` it depends on `chef_version '>= 12.10.48' if respond_to?(:chef_version)`, but this version of Chef comes with embedded Ruby < `2.2.2` (2.1.9 I think). Chef's embedded Ruby is used to install `chef-sugar`, I believe it's a case when there is no system Ruby available?

I got it working with Chef version being at least `12.14.60` (which ships with Ruby 2.3.1)

**Comment by kzw** [comment]
Getting this problem too even though I have a case of chef-sugar 3.3.0 already installed in a machine with chef 12.11.18.  No idea how that was installed given this new error.  New installation (in kitchen with same version of chef) is failing with ruby dependency error.

**Comment by sethvargo** [comment]
[Chef 12 is EOL now](https://www.chef.io/eol-chef12-and-chefdk1/), so I think we just need to upgrade the Chef requirement.
