### ISSUE TITLE
Version 4.0.0 in Supermarket is different and does not install the gem

### ISSUE THREAD

**Issue by swdan** [sethvargo/chef-sugar#164]
Version 4.0.0 in supermarket is different and is missing "gem          'chef-sugar'" in metadata.rb. So the 4.0.0 version fails to install the gem and causes cookbooks that depend on the chef-sugar cookbook to fail. The 4.0.0 tagged in github seems to be the right version we need to get this correct version into supermarket.

**Comment by tas50** [comment]
This was actually a bug in stove where it skipped that metadata. 4.0.1 is up and has the metadata. Feel free to open this back up if you're still having problems with 4.0.1
