### ISSUE TITLE
Missing platform_family 'amazon' in linux? method

### ISSUE THREAD

**Issue by Sapr0** [sethvargo/chef-sugar#166]
In Ohai/Chef 13 and later, Amazon Linux will be identified as the platform_family 'amazon'.

However the `linux?` method doesn't include this option
https://github.com/sethvargo/chef-sugar/blob/master/lib/chef/sugar/platform_family.rb#L166

Would probably need a method of it's own as well.

**Comment by tas50** [comment]
#167 should fix this

**Comment by tas50** [comment]
Fixed in 4.1. Thanks for the report
