### ISSUE TITLE
Show non existing key in deep_fetch! error message

### ISSUE THREAD

**Issue by dennis-benzinger-hybris** [sethvargo/chef-sugar#86]
It would be nice if the error message generated by `deep_fetch!` would show which of the keys does not exist.
For example the error message for `deep_fetch!('level_1', 'level_2', 'missing', 'level_4')` would contain something like "node['level_1']['level_2']['missing'] does not exist".

**Comment by sethvargo** [comment]
@dennis-benzinger-hybris it does... or [at least it should](https://github.com/sethvargo/chef-sugar/blob/master/lib/chef/sugar/node.rb#L19-L28). Are you seeing something different? Can you show me some debug output?

**Comment by dennis-benzinger-hybris** [comment]
I did not test yet but how I understand the code and after reading your example on https://sethvargo.com/delicious-new-chef-sugars/ the error message shows all the keys. So you don't know at which level a key was missing.
