### ISSUE TITLE
Unacceptable breaking changes without a major version increment !!!

### ISSUE THREAD

**Issue by robcoward** [sethvargo/chef-sugar#97]
Come on @sethvargo - how on earth are we going to maintain a stable chef ecosystem without being able to rely on pessimistic cookbook version matching to prevent breaking changes in cookbooks from bringing down our infrastructure !?!?! 

If you need to release a breaking change, please bump the major version so we can rely on '~> 3.0.0' or even '~> 3.0' not breaking an otherwise stable chef converge.

**Comment by sethvargo** [comment]
Are you serious right now? Did you even read the changes?

In the future, please consider being less of a jerk. Thanks! :smile:

**Comment by robcoward** [comment]
I appreciate that you are pissed at chef right now for trampling over chef-sugar without warning, however what's the point of talking about semantic versioning and having concepts like pessimistic version matching if people don't stick to it.

In an international corporate environment, providing a service to customers, we need to maintain a stable enterprise-quality environment and have to be able to rely on things like pessimistic version matching to avoid breaking changes affecting our systems.

We haven't moved up to chef-client 12 yet, with a lot of our estate not even up to 11.16.4 ! Before you released your breaking change this afternoon, all our servers were quite happy, blissfully unaware of any chef12 issues. Now however, because we make extensive use of compile_time from chef-sugar, we are faced with updating a number of library cookbooks, rebuilding and testing new versions of ten times as many application cookbooks,  and then the associated environment cookbooks and managing the deployment of the new cookbooks via exponentially more chef environments !!!

So I don't consider myself being a jerk, just highlighting to you the unnecessary impact you have caused by releasing a breaking change and not sticking to semver.

**Comment by jtimberman** [comment]
@robcoward Why haven't you pinned your version of chef-sugar? Are you using any community cookbooks as well that implement `compile_time` (with or without `respond_to?` checks)? If not, I think you'll be safe by pinning your version of chef-sugar to 3.0.0. If you are, you probably should make sure you've pinned those cookbooks to versions that don't implement `compile_time` in any `chef_gem` resources.

**Comment by sethvargo** [comment]
@robcoward 

Okay, let's back up. First of all, I'm not "pissed" at Chef. Let's get that out of the way... I _am_ angry with you as a human being. You have absolutely no entitlement to speak to or treat someone with the complete lack of dignity and respect you have demonstrated here. No one! Even more-so, you have no right to degrade or insult the people who provide you with _free and open source_ software. None. Zero.

If you do not like Chef Sugar, then don't use it. I promise you, my feelings will not be hurt if you choose to use an alternative. I enjoy participating in healthy and happy communities. Your attitudes and actions compromise those very values, and I would strongly encourage you to reconsider your attitude, words, and actions towards others in the Chef community as this type of language and behavior is generally not tolerated (/cc @nathenharvey).

As representative of @nvmlabs (and @aunitt), you have portrayed your organization in a very negative light. You have verbally attacked the maintainer of software you use, and to what end? Do you feel better? Others are not the punching bags for your personal frustration. While I am sorry that you are frustrated and upset, I am not sympathetic to the attitude, actions, or words you have demonstrated here.

Nonetheless, I am _still_ going to try and help you. Nothing is _actually_ broken. If you are still on Chef 11.16.4, then Chef Sugar v3.0.1 is not breaking **anything** for you. For example, given the following recipe:

```ruby
include_recipe "chef-sugar::default"

compile_time do
  chef_gem "pry"
end
```

The output is as follows:

```text
-----> Starting Kitchen (v1.3.1)
-----> Converging <default-ubuntu-1204>...
       Preparing files for transfer
       Preparing dna.json
       Preparing current project directory as a cookbook
       Removing non-cookbook files before transfer
       Preparing solo.rb
-----> Chef Omnibus installation detected (11.16.4)
       Transferring files to <default-ubuntu-1204>
       Starting Chef Client, version 11.16.4
       Compiling Cookbooks...
       Recipe: chef-sugar::default
         * chef_gem[chef-sugar] action nothing (skipped due to action :nothing)
         * chef_gem[chef-sugar] action install (up to date)
       [2015-03-20T20:51:40+00:00] WARN:
       The Chef Sugar recipe DSL method `compile_time' has been renamed to
       `at_compile_time'! This is a breaking change that was released in a patch
       version, so please continue reading to understand the necessary semantic
       versioning violation.

       Despite having existed since October 15, 2013 (b4d4c0e) and being one of the
       most widely used cookbooks in the Chef ecosystem, Chef Software decided to
       implement their own version of `compile_time' in Chef 12.1, breaking any cookbook
       that uses or depends on Chef Sugar on Chef 12.1:

           https://www.chef.io/blog/2015/03/03/chef-12-1-0-released

       As is common with Chef-ecosystem tooling, no warning was given, and maintainers
       are left to pick up the pieces from upset Chef users who get rather bespoke
       error messages now:

           https://github.com/sethvargo/chef-sugar/issues/89
           https://github.com/opscode-cookbooks/xml/issues/22
           https://github.com/opscode-cookbooks/aws/pull/110

       In order to progress Chef Sugar forward, the DSL method has been renamed to
       avoid the namespace collision.

       In short, you should change this:

           compile_time do
             # ...
           end

       to this:

           at_compile_time do
             # ...
           end

       You are running a version of Chef Client that does not include the
       `compile_time' attribute on core Chef resources (most likely less than
       Chef 12.1), so this is just a warning. Please consider changing the Chef Sugar
       `compile_time' method to `at_compile_time' in your Chef recipes. If you upgrade
       Chef, your recipes WILL break.

         * chef_gem[pry] action install (up to date)
         * chef_gem[pry] action install (up to date)
         Converging 2 resources
         * chef_gem[chef-sugar] action nothing (skipped due to action :nothing)
         * chef_gem[pry] action nothing (skipped due to action :nothing)

       Running handlers:
       Running handlers complete
       Chef Client finished, 0/3 resources updated in 1.076749541 seconds
       Finished converging <default-ubuntu-1204> (0m3.40s).
```

Notice the "WARN"? It does not say "ERROR" it does not say "FATAL", it says warn. Meaning this is a _warning_. 

Following that, the output shows:

```text
         * chef_gem[pry] action install (up to date)
         * chef_gem[pry] action install (up to date)
```

Those lines indicate your previous code is _working as it previously did_. I believe the warning output is very clear:

```text
You are running a version of Chef Client that does not include the
`compile_time' attribute on core Chef resources (most likely less than
Chef 12.1), so this is just a warning. Please consider changing the Chef Sugar
`compile_time' method to `at_compile_time' in your Chef recipes. If you upgrade
Chef, your recipes WILL break.
```

> We haven't moved up to chef-client 12 yet, with a lot of our estate not even up to 11.16.4 !

That's great! As I demonstrated here, nothing is broken! Your Chef Client runs are going to have a bit more output, but that's it.

> Before you released your breaking change this afternoon, all our servers were quite happy, blissfully unaware of any chef12 issues.

Are you actually experiencing issues or are you assuming you are going to have issues by reading the changeset? I cannot get Chef Sugar to error on Chef 11.x - I tested literally every released version. Perhaps if you are using Chef Sugar internals as a library, you may experience issues, but relying on the internals of a gem is never safe. The public API is clearly documented and anything outside of that API is considered unsafe.

> Now however, because we make extensive use of compile_time from chef-sugar, we are faced with updating a number of library cookbooks, rebuilding and testing new versions of ten times as many application cookbooks, and then the associated environment cookbooks and managing the deployment of the new cookbooks via exponentially more chef environments !!!

A few things:

1. When you end a sentence in `!!!`, it sounds like you are yelling, much like when someone writes in ALL CAPS. It conveys emotions of anger making it very difficult for others to share empathy in your words.
1. As I have demonstrated above (and for the record - this is something I tested prior to releasing the new version) - Chef 11.x's behavior is unaffected by this new version. It behaves exactly the same as before, just outputting a warning message that, when you upgrade to Chef 12, you are going to have a bad day unless you make some changes first.

In closing, I am sorry this might have caused you issues. I hope you will re-consider your tact and approach when speaking to others in the future.

**Comment by nathenharvey** [comment]
The [Chef Community Guidelines](https://docs.chef.io/community_guidelines.html) include the following:
* Be welcoming, inclusive, friendly, and patient.
* Be considerate.
* Be respectful.
* Be professional.
* Be careful in the words that you choose.
* When we disagree, let’s all work together to understand why.

There's clearly a disagreement here and I would love to help understand why there's disagreement and see if there's a way that it can be resolved.

Issues, bugs, and breaking changes are to be expected with any software.  Can we work together to make sure that we can make dealing with those things easier?  

How can I help?

**Comment by robcoward** [comment]
@sethvargo, i apologise if the exclaimation marks come across as shouting. After 2 decades of working in the  industry, it still frustrates me when software updates are released late on a friday, just before everyone disappears for the weekend, leaving systems broken unless someone stays late to sort them out. In a traditional release management scenario, that's poor process management, however in the brave new world of automation the lines are a little more blurred.

@jtimberman we do use the environment cookbook pattern to control cookbook deployments through our software delivery pipeline, so we do have explicit versions 
pinned on our servers, however in our application and llibrary cookbooks we only use pessimistic constraints so we can automatically benefit from minor releases and bug fixes with some comfort that semver versioning on community cookbooks wouldn't introduce a breaking change - we expect that depends 'some-cookbook', '~> 3.0.0' should be sufficient.

What broke this afternoon was our CI builds running test-kitchen against cookbook changes, where berkshelf pulled in the new release of chef-sugar since the pessimistic constraint was still satisfied. It was one of my collegues that was investigating the failures, so i only heard 2nd hand that chef-sugar had been updated and that was what was causing the test-kitchen converge to fail. I dont have access to our jenkins server atm, so i will have to wait until monday morning to dig out the logs and take a look for myself.

What concerned me was the comments in the changelog when i looked, describing a breaking change, with a key resource being renamed and comments about a verbose error message, yet the major version was not bumped. Seeing @sethvargo 's kitchen output however, it seems our kitchen failures need further investigation.

**Comment by lamont-granquist** [comment]
@robcoward you are pinning the chef-client itself.  why are you not equality pinning the chef-sugar version in production?  if you have production servers which are auto updating themselves with no oversight and no testing pipeline that will always end badly.
